"""add brand segments

Revision ID: cfa16bcd274a
Revises: 54fb9519ea4e
Create Date: 2025-01-21 20:22:49.084112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cfa16bcd274a'
down_revision: Union[str, None] = '54fb9519ea4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('segment_male', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('brand', sa.Column('price_segment_male', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('brand', sa.Column('segment_female', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('brand', sa.Column('price_segment_female', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('customer', sa.Column('segments', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('customer', sa.Column('price_segments', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'price_segments')
    op.drop_column('customer', 'segments')
    op.drop_column('brand', 'price_segment_female')
    op.drop_column('brand', 'segment_female')
    op.drop_column('brand', 'price_segment_male')
    op.drop_column('brand', 'segment_male')
    # ### end Alembic commands ###

